Lesson 5: Add appeal form
pahanhik700/fefu_backend_2_3 pull request #7
Opened 2022-01-15 10:17 UTC by pahanhik700

2022-01-16 13:45 UTC, chrn-feip requested changes

2022-01-16 13:45 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +        @if (isset($errors['message']))
message?

2022-01-16 13:45 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +        <textarea class="bordered" name="message" maxlength="100" rows="7"></textarea>
Где тут old и сообщение об ошибке?

2022-01-16 13:45 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +        <label>Mail</label>
Mail - это почта, а не электронный почтовый адрес

2022-01-21 07:11 UTC, pahanhik700 commented
Исправил

2022-01-21 07:53 UTC, chrn-feip requested changes

2022-01-21 07:53 UTC, chrn-feip commented on resources/views/appeal.blade.php
> +        <textarea class="bordered" name="message" maxlength="100" rows="7" value="{{ request()->isMethod('POST') ? old('mail') : '' }}></textarea>
old для другого атрибута

2022-01-21 10:45 UTC, pahanhik700 commented on resources/views/appeal.blade.php
> +        <textarea class="bordered" name="message" maxlength="100" rows="7" value="{{ request()->isMethod('POST') ? old('mail') : '' }}></textarea>
исправил

2022-01-21 10:58 UTC, merged